import moment from 'moment'
const state = {
    isWeekLoading: false,
    isMonthLoading: false,
    weeksets: [],
    employeesWeeksets: [],
    weekset: {},
    editingWeekset: {},
    newWeekset: {
        employee_comment: '',
        end_date: '',
        manager_comment: null,
        start_date: moment().startOf('isoWeek').format('YYYY-MM-DD'),
        status: 'pending',
        weekset_name: '',
    },
    newWeeksetWeekYear: {
        week: moment().isoWeek(),
        year: moment().isoWeekYear(),
    },
    weeksetsLoading: false,
    comparingWeekset: null,
    availabilityDate: moment().format('YYYY-MM-DD'),
    previousDate: null,
    weeklyOverviewPanel: {
        show: false,
    },
    employeesWeekAvailabilities: [],
    availabilityTimeBlocks: [],
    availabilityWeeksetTimeBlocks: [],
    availabilityNewWeeksetTimeBlocks: [],
    availabilityEmployeeId: 0,
    deletedLocalAvailabilities: [],
    modifiedLocalAvailabilities: [],
    createdLocalAvailabilities: [],
    weeksetChanges: [],
    placeholderTimeblock: {
        placeholder: true,
        accountId: 0,
        date: moment(),
        editable: true,
        id: 0,
        priority: 0,
        repeat: false,
        timeFrom: '07:00',
        timeTo: '08:00',
        type: 'preferred',
        travel: {
            before: '00:30',
            after: '00:30',
        },
        icon: 'check',
    },
    availabilityForm: {
        date: moment(),
        type: {
            label: '',
            key: '',
            disabled: false,
        },
        time: {
            from: '',
            to: '',
        },
        travel: {
            before: '0:30',
            after: '0:30',
        },
        lessonHours: '1:00',
    },
    timeBlockTypes: [
        'preferred',
        'agreed',
        'school',
        'sport',
        'other',
    ],
    activeTimeblock: {},
    availabilityPopoverVisible: false,
    chooseAvailabilityTypePopoverVisible: false,
    newTimeBlockPosition: null,
    currentFormRect: null,
    activeSidePanel: '',
    sidePanels: {
        NEW: 'new',
        EDIT: 'edit',
        INFO: 'info',
        WEEKLY_OVERVIEW: 'weekly-overview',
        WEEKLY_DETAILS: 'weekly-details',
        NEW_WEEKSET: 'new-weekset',
    },
}
export default state
